### ISSUE TITLE
put it into hackage ?

### ISSUE THREAD

**Issue by teto** [rdnetto/powerline-hs#15]
Hi,

My distribution (www.nixos.org) picks up automatically packages that are on hackage. It would be cool if you could publish powerline-hs there ? It might be relevant for other usecases too.

**Comment by rdnetto** [comment]
So, the problem with this is that (as I understand it) the Nix expressions for Hackage packages are compiled against the latest versions of all their dependencies. That would mean I'd need to commit to continuing to bump dependencies and resolve incompatibilities. That would have been justified for a library, where downstream consumers need that ongoing work to consume it alongside other new libraries, but there's no point for something which is just an executable, especially as I haven't actively worked on it in over a year.

If you want a Nix expression for powerline-hs, I think a better course of action would be generating it using stackage2nix - that way it continues to be built against the same library versions, without the need for ongoing maintenance.

**Comment by teto** [comment]
I see your point. Thanks for the explanation.
