### ISSUE TITLE
Can't find powerline folder on nix

### ISSUE THREAD

**Issue by teto** [rdnetto/powerline-hs#6]
I am trying to install powerline-hs as a way to learn haskell. I am on nixos, trying to compile powerline-hs from source.
When I run `cabal build` I get:
```
Preprocessing executable 'powerline-hs' for powerline-hs-0.1.0.1..
Building executable 'powerline-hs' for powerline-hs-0.1.0.1..
[ 6 of 19] Compiling Config.PowerlineResources ( src/Config/PowerlineResources.hs, dist/build/powerline-hs/powerline-hs-tmp/Config/PowerlineResources.o )

src/Config/PowerlineResources.hs:14:28: error:
    • Exception when trying to run compile-time code:
        ./powerline/powerline/config_files: getDirectoryContents:openDirStream: does not exist (No such file or directory)
      Code: embedDir "./powerline/powerline/config_files"
    • In the untyped splice:
        $(embedDir "./powerline/powerline/config_files")
   |
14 | configFiles = Map.fromList $(embedDir "./powerline/powerline/config_files")
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

My powerline installation is (nix paths are kinda cryptic) at:
/nix/store/l0gn07a7cqc516an6ag7aq11k3y1wypz-python3.6-powerline-2.6
Is there a way to specify the powerline dir via a build switch --powerline-dir=... for instance ?

Also glob-posix tests fail on nix ($HOME and /usr/local don't exist) so I had to disable its tests.

**Comment by teto** [comment]
arf I had checked for submodules with `git submodule summary` and deduced there was none since the output got null, checking on github UI, I saw the submodule, fetched it and it fixed the problem

**Comment by rdnetto** [comment]
For future reference, you might find it useful to setup an alias like `gcl='git clone --recursive'`. The `--recursive` flag will always pull down any submodules required.
