### ISSUE TITLE
Add support to show count of git commits ahead of remote branch

### ISSUE THREAD

**Issue by CarlosMChica** [rdnetto/powerline-hs#7]
Would there be interest to add support for this feature? In that case, I will probably send a PR.

**Comment by rdnetto** [comment]
Sure, as long as you take the following into account:
* the setting to enable it should not collide with any existing config options used by powerline
* we currently rely on Powerline to document the configuration options. If this is a Powerline-hs specific feature, you'll need to add documentation for it (a new Markdown file with a link from the README should do it)
* how expensive is this to determine in large repositories? (e.g. Linux kernel) Does it need a timeout?

**Comment by CarlosMChica** [comment]
Hey, I just started having a look and found out this segment for the original powerline https://github.com/jaspernbrouwer/powerline-gitstatus.

This does what I was asking for and much more. My assumption is that ideally, we would rewrite the gitstatus segment completely, however, I don't really have the time to add all of the features, at least not in one go. 

I propose the following:
* Reuse powerline gitstatus configuration options.
* Add features in an iterative fashion, starting with the commits ahead of remote.

I will start having a look at the code under the assumptions above. Please let me know if that makes sense to you.

**Comment by CarlosMChica** [comment]
https://github.com/rdnetto/powerline-hs/pull/8
